/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import app.Menu;
import app.Pegawai;
import app.Pelanggan;
import database.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 * GUI CarsierPage
 * @author Kelompok2_RestoranMamak
 */
public class CasierPage extends javax.swing.JFrame {
    Database dbms = new Database();
    int current_cust;
    int total_bill;
    private ArrayList<Menu> dataMenu = new ArrayList<Menu>();
    private ArrayList<Pegawai> dataPegawai = new ArrayList<Pegawai>();
    private ArrayList<Pelanggan> dataPelanggan = new ArrayList<Pelanggan>();
    
    /**
     * Creates new form CasierPage
     */
    public CasierPage() {
        initComponents();
        dataMenu = dbms.getMenu();
        add_pelanggan.setEnabled(false);
        
        System.out.println(dataMenu.get(0).getName());
        for(int i = 0;i < dataMenu.size();i++){
            System.out.println(dataMenu.get(i).getName());
            add_makanan_combo.addItem(dataMenu.get(i).getName());
        }
        
        add_makanan_combo.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListCust = new javax.swing.JList<>();
        del_cust_name = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pay_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_pesanan = new javax.swing.JTable();
        del_order_btn = new javax.swing.JButton();
        add_order_btn = new javax.swing.JButton();
        nama_label = new javax.swing.JLabel();
        takeaway_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        banyak_pesan = new javax.swing.JTextField();
        add_makanan_combo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        total_belanja = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama_pelanggan_input = new javax.swing.JTextField();
        add_pelanggan = new javax.swing.JButton();
        takeaway_input = new javax.swing.JCheckBox();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casier");
        setPreferredSize(new java.awt.Dimension(1080, 730));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Kasir Restoran Mamak");

        ListCust.setPreferredSize(new java.awt.Dimension(53, 50));
        ListCust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListCustMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListCust);

        del_cust_name.setText("Del");
        del_cust_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_cust_nameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Data Pelanggan");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Takeaway");

        pay_btn.setText("Bayar");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        table_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pesanan", "Harga", "Banyak", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_pesanan.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table_pesanan);
        if (table_pesanan.getColumnModel().getColumnCount() > 0) {
            table_pesanan.getColumnModel().getColumn(0).setResizable(false);
            table_pesanan.getColumnModel().getColumn(1).setResizable(false);
            table_pesanan.getColumnModel().getColumn(2).setResizable(false);
            table_pesanan.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        del_order_btn.setText("Del");
        del_order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_order_btnActionPerformed(evt);
            }
        });

        add_order_btn.setText("Add");
        add_order_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_order_btnActionPerformed(evt);
            }
        });

        nama_label.setText("null");

        takeaway_label.setText("null");

        jLabel7.setText("Banyak");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel8.setText("TOTAL Rp.");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        total_belanja.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(takeaway_label)
                                            .addComponent(nama_label)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(add_makanan_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(banyak_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(add_order_btn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(del_order_btn)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_belanja, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(takeaway_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_makanan_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(banyak_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_order_btn)
                    .addComponent(del_order_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pay_btn)
                    .addComponent(total_belanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jLabel5.setText("Add Customer");

        nama_pelanggan_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pelanggan_inputActionPerformed(evt);
            }
        });
        nama_pelanggan_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nama_pelanggan_inputKeyReleased(evt);
            }
        });

        add_pelanggan.setText("Add");
        add_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pelangganActionPerformed(evt);
            }
        });

        takeaway_input.setText("Takeaway");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(nama_pelanggan_input, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(takeaway_input)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(add_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(del_cust_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_pelanggan_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(takeaway_input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_pelanggan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(del_cust_name))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void del_cust_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_cust_nameActionPerformed
        DefaultListModel model = (DefaultListModel) ListCust.getModel();
        int selectedIndex = ListCust.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
        }
        
        dataPelanggan.remove(selectedIndex);
        DefaultTableModel mdl = (DefaultTableModel)table_pesanan.getModel();
        while(mdl.getRowCount() > 0){
            mdl.removeRow(0);
        }
        add_makanan_combo.setSelectedIndex(-1);
        banyak_pesan.setText(null);
        nama_label.setText(null);
        takeaway_label.setText(null);
        
        this.updateTotal();
    }//GEN-LAST:event_del_cust_nameActionPerformed

    /**
     * Method 
     */
    private void ListCustMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListCustMouseClicked
        nama_label.setText(ListCust.getSelectedValue());
        takeaway_label.setText(dataPelanggan.get(ListCust.getSelectedIndex()).getTakeway() ? "Ya" : "Tidak");
        current_cust = ListCust.getSelectedIndex();
        
        DefaultTableModel model = (DefaultTableModel)table_pesanan.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        ArrayList<Menu> order = new ArrayList<Menu>();
        ArrayList<Integer> byk_pesanan = new ArrayList<Integer>();
        order = dataPelanggan.get(current_cust).getOrder();
        byk_pesanan = dataPelanggan.get(current_cust).getByk();
        for(int i = 0;i < order.size();i++){
            int ttl = order.get(i).getPrice()*byk_pesanan.get(i);
            model.addRow(new Object[]{order.get(i).getName(),order.get(i).getPrice(),byk_pesanan.get(i), ttl});
        }
       
        add_makanan_combo.setSelectedIndex(-1);
        banyak_pesan.setText(null);
        
        this.updateTotal();
    }//GEN-LAST:event_ListCustMouseClicked

    private void add_order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_order_btnActionPerformed
        Menu pesan = dataMenu.get(add_makanan_combo.getSelectedIndex());
        int byk = Integer.parseInt(banyak_pesan.getText());
        dataPelanggan.get(current_cust).addOrder(pesan);
        dataPelanggan.get(current_cust).setByk(byk);
        
        DefaultTableModel model = (DefaultTableModel)table_pesanan.getModel();
        while(model.getRowCount() > 0){
            model.removeRow(0);
        }
        
        ArrayList<Menu> order = new ArrayList<Menu>();
        ArrayList<Integer> byk_pesanan = new ArrayList<Integer>();
        order = dataPelanggan.get(current_cust).getOrder();
        byk_pesanan = dataPelanggan.get(current_cust).getByk();
        for(int i = 0;i < order.size();i++){
            int ttl = order.get(i).getPrice()*byk_pesanan.get(i);
            model.addRow(new Object[]{order.get(i).getName(),order.get(i).getPrice(),byk_pesanan.get(i), ttl});
        }
       
        add_makanan_combo.setSelectedIndex(-1);
        banyak_pesan.setText(null);
        
        this.updateTotal();
    }//GEN-LAST:event_add_order_btnActionPerformed

    private void del_order_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_order_btnActionPerformed
        DefaultTableModel model = (DefaultTableModel)table_pesanan.getModel();
        if(table_pesanan.getSelectedRow() != -1) {
               // remove selected row from the model
               dataPelanggan.get(current_cust).removeOrder(table_pesanan.getSelectedRow());
               model.removeRow(table_pesanan.getSelectedRow());
               JOptionPane.showMessageDialog(null, "Selected row deleted successfully");
            }
        
        this.updateTotal();
    }//GEN-LAST:event_del_order_btnActionPerformed

    private void add_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pelangganActionPerformed
        dataPelanggan.add(new Pelanggan(nama_pelanggan_input.getText(), takeaway_input.isSelected()));
        
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for(int i = 0;i < dataPelanggan.size();i++){
            model.addElement(dataPelanggan.get(i).getName());
        }
        ListCust.setModel(model);
        
        nama_pelanggan_input.setText(null);
        takeaway_input.setSelected(false);
        add_pelanggan.setEnabled(false);
    }//GEN-LAST:event_add_pelangganActionPerformed

    private void nama_pelanggan_inputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_pelanggan_inputKeyReleased
        if(nama_pelanggan_input.getText().length() > 0){
            add_pelanggan.setEnabled(true);
        }else{
            add_pelanggan.setEnabled(false);
        }
    }//GEN-LAST:event_nama_pelanggan_inputKeyReleased

    private void nama_pelanggan_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pelanggan_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pelanggan_inputActionPerformed

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
        Bayar byr = new Bayar(total_bill);
        byr.setVisible(true);
        
        DefaultListModel model = (DefaultListModel) ListCust.getModel();
        int selectedIndex = ListCust.getSelectedIndex();
        if (selectedIndex != -1) {
            model.remove(selectedIndex);
        }
        
        dataPelanggan.remove(selectedIndex);
        DefaultTableModel mdl = (DefaultTableModel)table_pesanan.getModel();
        while(mdl.getRowCount() > 0){
            mdl.removeRow(0);
        }
        add_makanan_combo.setSelectedIndex(-1);
        banyak_pesan.setText(null);
        nama_label.setText(null);
        takeaway_label.setText(null);
        
        this.updateTotal();
    }//GEN-LAST:event_pay_btnActionPerformed

    private void updateTotal(){
        total_bill = 0;
                
        DefaultTableModel mdl = (DefaultTableModel)table_pesanan.getModel();
        for (int i = 0; i < mdl.getRowCount(); i++){
            System.out.println(mdl.getValueAt(i, 3));
            int amount = Integer.parseInt(String.valueOf(mdl.getValueAt(i, 3)));
            total_bill += amount;
        }
        System.out.println(total_bill);
        total_belanja.setText(String.valueOf(total_bill));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CasierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CasierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CasierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CasierPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasierPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListCust;
    private javax.swing.JComboBox<String> add_makanan_combo;
    private javax.swing.JButton add_order_btn;
    private javax.swing.JButton add_pelanggan;
    private javax.swing.JTextField banyak_pesan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton del_cust_name;
    private javax.swing.JButton del_order_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nama_label;
    private javax.swing.JTextField nama_pelanggan_input;
    private javax.swing.JButton pay_btn;
    private javax.swing.JTable table_pesanan;
    private javax.swing.JCheckBox takeaway_input;
    private javax.swing.JLabel takeaway_label;
    private javax.swing.JLabel total_belanja;
    // End of variables declaration//GEN-END:variables
}
